---
- name: install nginx
  yum: name=nginx state=latest

- name: remove nginx default config
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: copy nginx config
  template: src={{ item.src }} dest={{ item.dest }}
  with_items: "{{ nginx_conf_templates }}"
  notify:
    - restart nginx
